name: Trivy Scan

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv trivy /usr/local/bin/

    - name: Run Trivy scan
      run: |
        mkdir -p reports
        trivy image --format template --template "@/html.tpl" \
          -o reports/trivy-report-$(date +%F-%H%M).html debian:bookworm

    - name: Commit and Push Report
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add reports/
        git commit -m "Add Trivy scan report [skip ci]" || echo "No changes to commit"
        git push origin HEAD:main
